[server]
headless = true
fileWatcherType = "none"
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3B82F6"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#18181B"
textColor = "#FAFAFA"
font = "sans serif"
